aspnetboilerplate/module-zero-core-template

src/AbpCompanyName.AbpProjectName.Core/Localization/SourceFiles/AbpProjectName-nl-NL.xml, src/AbpCompanyName.AbpProjectName.EntityFramework/Migrations/SeedData/DefaultLanguagesCreator.cs
Added Dutch language file and the line of code to add the language to the database table on intitial seed.
=> Added Dutch language

aspnet-core/src/AbpCompanyName.AbpProjectName.Core/Web/WebContentFolderHelper.cs
I am not sure we will be able to use `dotnet ef database update` in Linux yet but this was a show-stopper, so let's fix that first.
=> Combine paths in cross-platform style to allow Ef migrations in Linux

aspnet-core/src/AbpCompanyName.AbpProjectName.Core/Authorization/Users/UserRegistrationManager.cs
Fixed Register() to use isEmailConfirmed flag in method parameter
=> Fixed Register() with isEmailConfirmed flag

aspnet-core/src/AbpCompanyName.AbpProjectName.Core/Localization/SourceFiles/AbpProjectName.xml
See: [AccountController.cs#L296](https://github.com/aspnetboilerplate/module-zero-core-template/blob/cdd334959c650568e556cd0b40cfe00595250c81/aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Controllers/AccountController.cs#L296)
=> Add missing localization used in AccountController

aspnet-core/src/AbpCompanyName.AbpProjectName.Application/AbpProjectNameApplicationModule.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.Application/Roles/Dto/RoleMapProfile.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.Application/Users/Dto/UserMapProfile.cs
@hikalkan  - not sure if you think this is a better way to configure automapper?
=> Automapper config change

aspnet-core/src/AbpCompanyName.AbpProjectName.Core/Localization/SourceFiles/AbpProjectName-lt.xml
=> Updated Lithuanian translations

aspnet-core/src/AbpCompanyName.AbpProjectName.Application/Roles/RoleAppService.cs
[AbpRoleManager.cs#L287-L290](https://github.com/aspnetboilerplate/aspnetboilerplate/blob/b32fc1e6e0d8922029944ce42143c5329b78c64a/src/Abp.ZeroCore/Authorization/Roles/AbpRoleManager.cs#L287-L290)
=> Remove duplicate check done in AbpRoleManager

angular/.angular-cli.json, angular/e2e/app.e2e-spec.ts, angular/package.json
Only last entry is related to this repo. Also others fixed in private repo.
=> Fixed #136 - Some issues with a freshly generated project from template.

aspnet-core/NuGet.Config
Fixes aspnetboilerplate/aspnetboilerplate#2831
=> Add NuGet package source

aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/compilerconfig.json
Removed main.css from compiler config which suppose to be in the commit  4ce876673240abfba012a0a9b9504f80d1091381
=> Update compiler config

aspnet-core/src/AbpCompanyName.AbpProjectName.Migrator/MultiTenantMigrateExecuter.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.Migrator/Program.cs
=> Fixed #175 - Hide connection string from migrator output

aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Core/Authentication/JwtBearer/JwtTokenMiddleware.cs
As mentioned in https://github.com/aspnetboilerplate/aspnetboilerplate/issues/2836
It will be good if custom Jwt `AuthenticationScheme` is configurable by default
=> Custom Jwt AuthencationScheme

aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Host/Startup/SecurityRequirementsOperationFilter.cs
Even if AbpAuthorizeAttribute has no Permissions, the Api/Action on swagger-ui should also has Security property.
=> fix swagger-ui

aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Views/Shared/_Layout.cshtml
- Fixed PleaseWait localization
- Removed extra semicolon
=> Fixed _Layout.cshtml for Mvc project

aspnet-core/src/AbpCompanyName.AbpProjectName.Core/Localization/SourceFiles/AbpProjectName-pt-BR.xml, aspnet-core/src/AbpCompanyName.AbpProjectName.Core/Localization/SourceFiles/AbpProjectName.xml, aspnet-core/src/AbpCompanyName.AbpProjectName.EntityFrameworkCore/EntityFrameworkCore/Seed/Host/DefaultLanguagesCreator.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Views/Account/_Layout.cshtml, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Views/Roles/Index.cshtml, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Views/Roles/_EditRoleModal.cshtml, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Views/Shared/Components/RightSideBar/Default.cshtml, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Views/Shared/_Layout.cshtml, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Views/Tenants/Index.cshtml, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Views/Users/Index.cshtml, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Views/Users/_EditUserModal.cshtml, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/wwwroot/index.html, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/wwwroot/view-resources/Views/Roles/Index.js, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/wwwroot/view-resources/Views/Tenants/Index.js, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/wwwroot/view-resources/Views/Users/Index.js
Removing harded code strings
Adding jQuery validations localization
Updating PT-BR translations
=> PT-BR update, remove many hardcoded strings and enable jquery validation localization

angular/src/app/layout/topbar.component.html
Fixes: [How to navigate to Home page from Application logo?](https://stackoverflow.com/q/50270123/8601760)
> `asp-controller` and `asp-action` are [Tag Helpers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/working-with-forms?view=aspnetcore-2.1).
>
> For an Angular component, use the [`routerLink`](https://angular.io/api/router/RouterLink#description) attribute.
=> Fix navigate to Home page from Application logo

aspnet-core/src/AbpCompanyName.AbpProjectName.Application/AbpCompanyName.AbpProjectName.Application.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Core/AbpCompanyName.AbpProjectName.Core.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.EntityFrameworkCore/AbpCompanyName.AbpProjectName.EntityFrameworkCore.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Migrator/AbpCompanyName.AbpProjectName.Migrator.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Core/AbpCompanyName.AbpProjectName.Web.Core.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Host/AbpCompanyName.AbpProjectName.Web.Host.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/AbpCompanyName.AbpProjectName.Web.Mvc.csproj, aspnet-core/test/AbpCompanyName.AbpProjectName.Tests/AbpCompanyName.AbpProjectName.Tests.csproj
Fixes 
- Upgrade asp.net core to v2.1 #261
- Upgrade APB to 3.7 #260
=> Package upgrades

aspnet-core/src/AbpCompanyName.AbpProjectName.EntityFrameworkCore/EntityFrameworkCore/Repositories/AbpProjectNameRepositoryBase.cs
As suggested in:
- https://github.com/aspnetboilerplate/aspnetboilerplate/issues/712#issuecomment-376258476
- https://github.com/aspnetboilerplate/aspnetboilerplate/issues/3364#issuecomment-390399191
=> Make RepositoryBase implement IRepository<TEntity>

angular/src/app/app-routing.module.ts, angular/src/app/roles/roles.component.ts, angular/src/app/tenants/tenants.component.ts, angular/src/app/users/users.component.ts, angular/src/shared/auth/auth-route-guard.ts, angular/src/shared/paged-listing-component-base.ts, angular/src/shared/shared.module.ts
=> Use single quotes for Angular imports

angular/src/AppPreBootstrap.ts, angular/src/app/layout/sidebar-user-area.component.html, angular/src/environments/environment.hmr.ts, angular/src/environments/environment.prod.ts, angular/src/environments/environment.ts, angular/src/root.module.ts, angular/src/shared/AppConsts.ts, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Host/Startup/Startup.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Host/wwwroot/swagger/ui/index.html
Fixes https://github.com/aspnetboilerplate/module-zero-core-template/issues/250
=> Problems on hosting in a sub-website

aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/wwwroot/js/admin.js
Fixes #292 
Included active parent menu item with dom traversal
=> Enable parent menu items of active sub menu item

aspnet-core/src/AbpCompanyName.AbpProjectName.Application/MultiTenancy/TenantAppService.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.Application/Users/UserAppService.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.Core/Authorization/Users/UserRegistrationManager.cs
fix #332
Call `UserManager.InitializeOptionsAsync(tenantId); `override the identity default specification
=> fix #332 call UserManager.InitializeOptionsAsync(tenantId);

angular/src/account/register/register.component.html, angular/src/app/tenants/create-tenant/create-tenant.component.html, angular/src/app/users/create-user/create-user.component.html, angular/src/app/users/edit-user/edit-user.component.html, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Models/Account/RegisterViewModel.cs
See https://forum.aspnetboilerplate.com/viewtopic.php?p=31427
As used in:
https://github.com/aspnetboilerplate/module-zero-core-template/blob/63f6e3b6147b6df7a08b09a53dad562c57dac17c/aspnet-core/src/AbpCompanyName.AbpProjectName.Core/Validation/ValidationHelper.cs#L8
=> Add plus sign and apostrophe to email pattern

vue/src/components/fullscreen.vue
=> Declare global interface for Document

aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Views/Shared/Components/SideBarUserArea/Default.cshtml
fix #353 SideBarUserArea needs to handle the case of not logging in.
=> fix #353 SideBarUserArea needs to handle the case of not logging in.

angular/src/app/roles/roles.component.html, angular/src/app/roles/roles.component.ts, angular/src/app/tenants/tenants.component.html, angular/src/app/tenants/tenants.component.ts, angular/src/app/users/users.component.html, angular/src/app/users/users.component.ts, angular/src/shared/service-proxies/service-proxies.ts, aspnet-core/src/AbpCompanyName.AbpProjectName.Application/Users/Dto/PagedUserResultRequestDto.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.Application/Users/UserAppService.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.Core/Localization/SourceFiles/AbpProjectName.xml, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Host/appsettings.json, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Host/web.config
Implements list query filter for users/roles/tenants in angular template
1. Users with Keyword and IsActive filter
1. Roles with Keyword filter
1. Tenants with Keyword and IsActive filter
=> Implements list query filter for users/roles/tenants in angular template 

aspnet-core/src/AbpCompanyName.AbpProjectName.Application/Users/Dto/UserMapProfile.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.Core/AbpCompanyName.AbpProjectName.Core.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Core/Authorization/Users/UserStore.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.EntityFrameworkCore/Migrations/20190208051931_Upgrade_ABP_4_2_0.Designer.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.EntityFrameworkCore/Migrations/20190208051931_Upgrade_ABP_4_2_0.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.Migrator/AbpCompanyName.AbpProjectName.Migrator.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Core/AbpCompanyName.AbpProjectName.Web.Core.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Host/AbpCompanyName.AbpProjectName.Web.Host.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/AbpCompanyName.AbpProjectName.Web.Mvc.csproj, aspnet-core/test/AbpCompanyName.AbpProjectName.Tests/AbpCompanyName.AbpProjectName.Tests.csproj
=> Upgrade abp to v4.2.0

aspnet-core/src/AbpCompanyName.AbpProjectName.Core/Authorization/Users/User.cs
fix #407 
Initialize User Roles under CreateTenantAdminUser method.
=> Initialize User Roles under CreateTenantAdminUser method.

reactjs/src/scenes/Users/index.tsx
dataIndex and Key for EmailAddress fixed.
=> Users list: incorrect value in EmailAddress column

aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Core/Controllers/TokenAuthController.cs
Not important it just trigger my ocd! :)
=> TokenAuthController typo GetEncrpyedAccessToken => GetEncryptedAccessToken

angular/src/app/roles/create-role/create-role-dialog.component.ts, angular/src/app/roles/edit-role/edit-role-dialog.component.ts, angular/src/shared/service-proxies/service-proxies.ts, aspnet-core/src/AbpCompanyName.AbpProjectName.Application/Roles/Dto/CreateRoleDto.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.Application/Roles/Dto/RoleDto.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.Application/Roles/Dto/RoleMapProfile.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.Application/Roles/RoleAppService.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/wwwroot/view-resources/Views/Roles/Index.js, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/wwwroot/view-resources/Views/Roles/_EditRoleModal.js, reactjs/src/models/Roles/roleModel.ts, reactjs/src/scenes/Roles/components/createOrUpdateRole.tsx, reactjs/src/scenes/Roles/components/createOrUpdateRole.validation.ts, reactjs/src/scenes/Roles/index.tsx, reactjs/src/services/role/dto/createRoleInput.ts, reactjs/src/services/role/dto/createRoleOutput.ts, reactjs/src/services/role/dto/getAllRoleOutput.ts, reactjs/src/services/role/dto/getRoleAsyncOutput.ts, reactjs/src/services/role/dto/getRoleForEditOutput.ts, reactjs/src/services/role/dto/updateRoleInput.ts, reactjs/src/services/role/dto/updateRoleOutput.ts, reactjs/src/services/user/dto/getRolesOuput.ts, reactjs/src/stores/roleStore.ts, vue/src/store/entities/role.ts, vue/src/views/setting/role/create-role.vue, vue/src/views/setting/role/edit-role.vue
=> Use GrantedPermissions instead of Permissions in Role.

aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Views/Shared/_Layout.cshtml
Since it has been injected in AbpRazorPage
https://github.com/aspnetboilerplate/aspnetboilerplate/blob/7415b118b18da94829c65b788730dc47cf8866b5/src/Abp.AspNetCore/AspNetCore/Mvc/Views/AbpRazorPage.cs#L47-L49
=> Remove unnecessary setting manager injection

angular/src/shared/helpers/SignalRAspNetCoreHelper.ts
resolve https://github.com/aspnetboilerplate/aspnetboilerplate/issues/4578
=> Modify the SignalR script loading method.

aspnet-core/src/AbpCompanyName.AbpProjectName.Application/AbpProjectNameAppServiceBase.cs
fix waiting to get current user, because not waiting a result and not throwing exception
=> fix awaiting to get current user, because not waiting a result

aspnet-core/src/AbpCompanyName.AbpProjectName.Core/AbpCompanyName.AbpProjectName.Core.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.EntityFrameworkCore/Migrations/20190719143908_Upgraded_To_Abp_4_8_0.Designer.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.EntityFrameworkCore/Migrations/20190719143908_Upgraded_To_Abp_4_8_0.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.Migrator/AbpCompanyName.AbpProjectName.Migrator.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Core/AbpCompanyName.AbpProjectName.Web.Core.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Host/AbpCompanyName.AbpProjectName.Web.Host.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/AbpCompanyName.AbpProjectName.Web.Mvc.csproj, aspnet-core/test/AbpCompanyName.AbpProjectName.Tests/AbpCompanyName.AbpProjectName.Tests.csproj
Abp packages are updated to 4.8.0.
=> abp packages are updated.

aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Host/Dockerfile, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Dockerfile
Resolve https://github.com/aspnetboilerplate/aspnetboilerplate/issues/4906
=> Update docker Image.

aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/wwwroot/view-resources/Views/Roles/Index.js, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/wwwroot/view-resources/Views/Shared/Components/TenantChange/Default.js, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/wwwroot/view-resources/Views/Tenants/Index.js, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/wwwroot/view-resources/Views/Users/Index.js
Resolve https://github.com/aspnetboilerplate/aspnetboilerplate/issues/4938
=> Override abp.ajax default dataType.

reactjs/craco.config.js
Resolve https://github.com/aspnetboilerplate/aspnetboilerplate/issues/4899
=> Fix the problem that the react template can't load the signalr.

aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Host/Controllers/HomeController.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Host/wwwroot/swagger/ui/abp.swagger.js, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Host/wwwroot/swagger/ui/index.html
Resolve https://github.com/aspnetboilerplate/aspnetboilerplate/issues/5004
=> Use AntiForgeryToken in swagger.

aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Host/wwwroot/swagger/ui/abp.swagger.js
close https://github.com/aspnetboilerplate/aspnetboilerplate/issues/5081
=> replaces manual json string creation with JSON.stringify

reactjs/src/components/Layout/AppLayout.tsx, reactjs/src/components/Router/NotFoundRoute.tsx
NotFound component added for not exist routes.
=> NotFound component added for not exist routes.

aspnet-core/src/AbpCompanyName.AbpProjectName.Core/AppVersionHelper.cs
Fixes [this](https://github.com/aspnetboilerplate/aspnetboilerplate/issues/4587)
=> AppVersionHelper.ReleaseDate cached

aspnet-core/src/AbpCompanyName.AbpProjectName.Core/AbpCompanyName.AbpProjectName.Core.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.EntityFrameworkCore/Migrations/20200220110527_Upgraded_To_Abp_5_2_0.Designer.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.EntityFrameworkCore/Migrations/20200220110527_Upgraded_To_Abp_5_2_0.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.Migrator/AbpCompanyName.AbpProjectName.Migrator.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Core/AbpCompanyName.AbpProjectName.Web.Core.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Host/AbpCompanyName.AbpProjectName.Web.Host.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/AbpCompanyName.AbpProjectName.Web.Mvc.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Startup/AbpProjectNameNavigationProvider.cs, aspnet-core/test/AbpCompanyName.AbpProjectName.Tests/AbpCompanyName.AbpProjectName.Tests.csproj
related: https://github.com/aspnetboilerplate/aspnetboilerplate/issues/5306
=> Upgrade ABP packages to v5.2.0

aspnet-core/src/AbpCompanyName.AbpProjectName.Application/Users/IUserAppService.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Controllers/UsersController.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Views/Shared/Components/RightNavbarUserArea/Default.cshtml, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Views/Users/ChangePassword.cshtml, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/bundleconfig.json, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/wwwroot/view-resources/Views/Users/ChangePassword.js
Fixes [this](https://github.com/aspnetboilerplate/aspnetboilerplate/issues/5249)
=> Change Password Page Added for MVC

aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Views/Account/_Layout.cshtml, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Views/Account/_Scripts.cshtml, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Views/Account/_Styles.cshtml, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Views/Shared/Layout/_Layout.cshtml, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Views/Shared/Layout/_Scripts.cshtml, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Views/Shared/Layout/_Styles.cshtml
Fixes [this](https://github.com/aspnetboilerplate/aspnetboilerplate/issues/5256)
=> mvc ui style and script referencing simplified

aspnet-core/src/AbpCompanyName.AbpProjectName.Core/AbpCompanyName.AbpProjectName.Core.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.EntityFrameworkCore/Migrations/20200320114152_Upgraded_To_Abp_5_4_0.Designer.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.EntityFrameworkCore/Migrations/20200320114152_Upgraded_To_Abp_5_4_0.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.Migrator/AbpCompanyName.AbpProjectName.Migrator.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Core/AbpCompanyName.AbpProjectName.Web.Core.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Host/AbpCompanyName.AbpProjectName.Web.Host.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/AbpCompanyName.AbpProjectName.Web.Mvc.csproj, aspnet-core/test/AbpCompanyName.AbpProjectName.Tests/AbpCompanyName.AbpProjectName.Tests.csproj
related https://github.com/aspnetboilerplate/aspnetboilerplate/issues/5417
=> Upgrade to Abp v5.4

aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/wwwroot/view-resources/Views/Roles/Index.js, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/wwwroot/view-resources/Views/Roles/_EditModal.js, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/wwwroot/view-resources/Views/Tenants/Index.js, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/wwwroot/view-resources/Views/Users/Index.js, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/wwwroot/view-resources/Views/Users/_EditModal.js
Using "$("input[name='role']:checked")" would return the all input element of the entire page(both CreateModal and EditModal).
=> fix User and Role view js error

aspnet-core/src/AbpCompanyName.AbpProjectName.Core/AbpCompanyName.AbpProjectName.Core.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.EntityFrameworkCore/AbpCompanyName.AbpProjectName.EntityFrameworkCore.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Migrator/AbpCompanyName.AbpProjectName.Migrator.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Core/AbpCompanyName.AbpProjectName.Web.Core.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Host/AbpCompanyName.AbpProjectName.Web.Host.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Host/Startup/Program.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Host/Startup/Startup.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Host/appsettings.json, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/AbpCompanyName.AbpProjectName.Web.Mvc.csproj, aspnet-core/test/AbpCompanyName.AbpProjectName.Tests/AbpCompanyName.AbpProjectName.Tests.csproj, aspnet-core/test/AbpCompanyName.AbpProjectName.Web.Tests/AbpCompanyName.AbpProjectName.Web.Tests.csproj
=> Update to Abp 5.6 & Fix Swagger UI for Kestrel web server

aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Views/Account/_Styles.cshtml, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Views/Shared/Layout/_Styles.cshtml, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Views/Users/_CreateModal.cshtml, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Views/Users/_EditModal.cshtml, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/bundleconfig.json, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/libman.json
Fixes [this](https://github.com/aspnetboilerplate/aspnetboilerplate/issues/5530).
=> Remove animate.css from mvc client

aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Views/Shared/Components/AccountLanguages/Default.cshtml, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Views/Shared/Components/RightNavbarLanguageSwitch/Default.cshtml
Resolve https://github.com/aspnetboilerplate/aspnetboilerplate/issues/5561
Require https://github.com/aspnetboilerplate/aspnetboilerplate/issues/5563
=> Include query string in return url for link to change culture

aspnet-core/src/AbpCompanyName.AbpProjectName.EntityFrameworkCore/EntityFrameworkCore/Seed/Host/DefaultLanguagesCreator.cs
Fixes [this](https://github.com/aspnetboilerplate/aspnetboilerplate/issues/5560).
=> change flag from uk to us

aspnet-core/src/AbpCompanyName.AbpProjectName.Core/AbpCompanyName.AbpProjectName.Core.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.EntityFrameworkCore/Migrations/20200604091046_Upgraded_To_Abp_5_9.Designer.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.EntityFrameworkCore/Migrations/20200604091046_Upgraded_To_Abp_5_9.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.Migrator/AbpCompanyName.AbpProjectName.Migrator.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Core/AbpCompanyName.AbpProjectName.Web.Core.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Host/AbpCompanyName.AbpProjectName.Web.Host.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/AbpCompanyName.AbpProjectName.Web.Mvc.csproj, aspnet-core/test/AbpCompanyName.AbpProjectName.Tests/AbpCompanyName.AbpProjectName.Tests.csproj, aspnet-core/test/AbpCompanyName.AbpProjectName.Web.Tests/AbpCompanyName.AbpProjectName.Web.Tests.csproj
Related https://github.com/aspnetboilerplate/aspnetboilerplate/issues/5636
=> upgrade-to-abp-5-9

aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Core/Models/TokenAuth/AuthenticateModel.cs
Resolve https://github.com/aspnetboilerplate/aspnetboilerplate/issues/5782
=> Ensure password is not audited during token authentication

angular/package.json, angular/src/account/layout/account-languages.component.ts, angular/src/app-initializer.ts, angular/src/app/layout/header-language-menu.component.ts, angular/src/app/roles/create-role/create-role-dialog.component.ts, angular/src/app/roles/edit-role/edit-role-dialog.component.ts, angular/src/app/users/create-user/create-user-dialog.component.ts, angular/src/app/users/edit-user/edit-user-dialog.component.ts, angular/src/root.module.ts, angular/yarn.lock
we should also move the imports from lodash to lodash-es.
bundle size before change the imports:
after:
=> move the imports from lodash to lodash-es

aspnet-core/AbpCompanyName.AbpProjectName.sln, aspnet-core/src/AbpCompanyName.AbpProjectName.Application/AbpCompanyName.AbpProjectName.Application.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Core/AbpCompanyName.AbpProjectName.Core.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Core/Authorization/Users/UserStore.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.EntityFrameworkCore/AbpCompanyName.AbpProjectName.EntityFrameworkCore.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.EntityFrameworkCore/Migrations/20201112121732_Upgraded_To_ABP_6_0.Designer.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.EntityFrameworkCore/Migrations/20201112121732_Upgraded_To_ABP_6_0.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.Migrator/AbpCompanyName.AbpProjectName.Migrator.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Core/AbpCompanyName.AbpProjectName.Web.Core.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Host/AbpCompanyName.AbpProjectName.Web.Host.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/AbpCompanyName.AbpProjectName.Web.Mvc.csproj, aspnet-core/test/AbpCompanyName.AbpProjectName.Tests/AbpCompanyName.AbpProjectName.Tests.csproj, aspnet-core/test/AbpCompanyName.AbpProjectName.Web.Tests/AbpCompanyName.AbpProjectName.Web.Tests.csproj
related https://github.com/aspnetboilerplate/aspnetboilerplate/issues/5878
=> Upgrade to abp 6 0

aspnet-core/src/AbpCompanyName.AbpProjectName.Application/Users/IUserAppService.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.Application/Users/UserAppService.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.Core/Authorization/AbpProjectNameAuthorizationProvider.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.Core/Authorization/PermissionNames.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.Core/Localization/SourceFiles/AbpProjectName.xml
Hello. 
I have added two Methods in UsersAppService.
Because there was one of the primary needs of mine in any application I have created by this template.
Secondly, this pull request is the starting point of the changes that I have made to this base repository. 
Is it ok to send pull requests to this repo?
=> Added activation api

aspnet-core/src/AbpCompanyName.AbpProjectName.Core/AbpProjectNameCoreModule.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.Core/Localization/SourceFiles/AbpProjectName-fa.xml, aspnet-core/src/AbpCompanyName.AbpProjectName.EntityFrameworkCore/EntityFrameworkCore/Seed/Host/DefaultLanguagesCreator.cs
Hi.
I have added the Persian translation to the localization of the project. 
I think there is no need to make any changes in Front-End projects or MVC.
Am I right?
=> Add Persian translation

aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Host/Startup/Startup.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Host/log4net.Production.config, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Host/log4net.config, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Startup/Startup.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/log4net.Production.config
related https://github.com/aspnetboilerplate/aspnetboilerplate/issues/5954 
related https://github.com/aspnetboilerplate/aspnetboilerplate/issues/5922
=> implement production config for log4net

aspnet-core/src/AbpCompanyName.AbpProjectName.Core/AbpCompanyName.AbpProjectName.Core.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.EntityFrameworkCore/Migrations/20201217144556_Upgrade_To_ABP_6_1_1.Designer.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.EntityFrameworkCore/Migrations/20201217144556_Upgrade_To_ABP_6_1_1.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.Migrator/AbpCompanyName.AbpProjectName.Migrator.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Core/AbpCompanyName.AbpProjectName.Web.Core.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Host/AbpCompanyName.AbpProjectName.Web.Host.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/AbpCompanyName.AbpProjectName.Web.Mvc.csproj, aspnet-core/test/AbpCompanyName.AbpProjectName.Tests/AbpCompanyName.AbpProjectName.Tests.csproj, aspnet-core/test/AbpCompanyName.AbpProjectName.Web.Tests/AbpCompanyName.AbpProjectName.Web.Tests.csproj
related https://github.com/aspnetboilerplate/aspnetboilerplate/issues/5942
=> Upgrade to ABP 6.1.1

aspnet-core/src/AbpCompanyName.AbpProjectName.Core/AbpCompanyName.AbpProjectName.Core.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Migrator/AbpCompanyName.AbpProjectName.Migrator.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Core/AbpCompanyName.AbpProjectName.Web.Core.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Host/AbpCompanyName.AbpProjectName.Web.Host.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/AbpCompanyName.AbpProjectName.Web.Mvc.csproj, aspnet-core/test/AbpCompanyName.AbpProjectName.Tests/AbpCompanyName.AbpProjectName.Tests.csproj, aspnet-core/test/AbpCompanyName.AbpProjectName.Web.Tests/AbpCompanyName.AbpProjectName.Web.Tests.csproj
related https://github.com/aspnetboilerplate/aspnetboilerplate/issues/5988
=> Upgrade abp packages

aspnet-core/src/AbpCompanyName.AbpProjectName.Core/AbpCompanyName.AbpProjectName.Core.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.EntityFrameworkCore/Migrations/20210324090321_Upgrade_To_ABP_6_3.Designer.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.EntityFrameworkCore/Migrations/20210324090321_Upgrade_To_ABP_6_3.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.Migrator/AbpCompanyName.AbpProjectName.Migrator.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Core/AbpCompanyName.AbpProjectName.Web.Core.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Host/AbpCompanyName.AbpProjectName.Web.Host.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/AbpCompanyName.AbpProjectName.Web.Mvc.csproj, aspnet-core/test/AbpCompanyName.AbpProjectName.Tests/AbpCompanyName.AbpProjectName.Tests.csproj, aspnet-core/test/AbpCompanyName.AbpProjectName.Web.Tests/AbpCompanyName.AbpProjectName.Web.Tests.csproj
Related https://github.com/aspnetboilerplate/aspnetboilerplate/issues/6073
=> Update to ABP 6.3

aspnet-core/src/AbpCompanyName.AbpProjectName.Core/Localization/SourceFiles/AbpProjectName-es.xml
The missing translations in Spanish were added to the localizer because in the Spanish version not all translations were shown.
=> completed translations in spanish

angular/package.json, angular/yarn.lock
Close https://github.com/aspnetboilerplate/aspnetboilerplate/issues/6119
=> Upgrade admin-lte-css-only to v3.0.5

aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Views/Shared/Layout/_Scripts.cshtml, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/bundleconfig.json, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/wwwroot/Common/datatables.ajax.js, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/wwwroot/Common/helpers.js, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/wwwroot/view-resources/Views/Roles/Index.js, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/wwwroot/view-resources/Views/Tenants/Index.js, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/wwwroot/view-resources/Views/Users/Index.js
close https://github.com/aspnetboilerplate/aspnetboilerplate/issues/2826
=> add html encode to ajax responses

aspnet-core/src/AbpCompanyName.AbpProjectName.Core/AbpCompanyName.AbpProjectName.Core.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Core/Authorization/Users/UserClaimsPrincipalFactory.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.Core/Editions/EditionManager.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.Core/Identity/SecurityStampValidator.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.EntityFrameworkCore/Migrations/20210628103231_Upgrade_To_ABP_6_4_rc1.Designer.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.EntityFrameworkCore/Migrations/20210628103231_Upgrade_To_ABP_6_4_rc1.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.Migrator/AbpCompanyName.AbpProjectName.Migrator.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Core/AbpCompanyName.AbpProjectName.Web.Core.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Host/AbpCompanyName.AbpProjectName.Web.Host.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/AbpCompanyName.AbpProjectName.Web.Mvc.csproj, aspnet-core/test/AbpCompanyName.AbpProjectName.Tests/AbpCompanyName.AbpProjectName.Tests.csproj, aspnet-core/test/AbpCompanyName.AbpProjectName.Web.Tests/AbpCompanyName.AbpProjectName.Web.Tests.csproj
related https://github.com/aspnetboilerplate/aspnetboilerplate/issues/6185
=> Upgrade to ABP 6.4.0-rc1

angular/src/account/tenant/tenant-change-dialog.component.ts, angular/src/app/roles/create-role/create-role-dialog.component.ts, angular/src/app/roles/edit-role/edit-role-dialog.component.ts, angular/src/app/tenants/create-tenant/create-tenant-dialog.component.ts, angular/src/app/tenants/edit-tenant/edit-tenant-dialog.component.ts, angular/src/app/users/create-user/create-user-dialog.component.ts, angular/src/app/users/edit-user/edit-user-dialog.component.ts, angular/src/app/users/reset-password/reset-password.component.ts
Fixes [#5652](https://github.com/aspnetboilerplate/aspnetboilerplate/issues/5652) and [here](https://github.com/aspnetboilerplate/module-zero-core-template/pull/547) is old closed pr.
=> Fixes unwanted modal delay on closing

aspnet-core/src/AbpCompanyName.AbpProjectName.Core/AbpCompanyName.AbpProjectName.Core.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Migrator/AbpCompanyName.AbpProjectName.Migrator.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Core/AbpCompanyName.AbpProjectName.Web.Core.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Host/AbpCompanyName.AbpProjectName.Web.Host.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/AbpCompanyName.AbpProjectName.Web.Mvc.csproj, aspnet-core/test/AbpCompanyName.AbpProjectName.Tests/AbpCompanyName.AbpProjectName.Tests.csproj, aspnet-core/test/AbpCompanyName.AbpProjectName.Web.Tests/AbpCompanyName.AbpProjectName.Web.Tests.csproj
related https://github.com/aspnetboilerplate/aspnetboilerplate/issues/6203
=> Upgrade to ABP 6.4.0

aspnet-core/src/AbpCompanyName.AbpProjectName.EntityFrameworkCore/EntityFrameworkCore/AbpProjectNameDbContextFactory.cs
close https://github.com/aspnetboilerplate/aspnetboilerplate/issues/6133
=> DB migration based on environment

aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/bundleconfig.json
close https://github.com/aspnetboilerplate/aspnetboilerplate/issues/6204
=> add signalr js files to shared-layout bundle

aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/bundleconfig.json
added missed js files in bundle config and ordered js files same as _Script.cshtml partial #6300,  fixed this issue https://github.com/aspnetboilerplate/aspnetboilerplate/issues/6300
=> added missed js files in bundle config  #6300

aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Startup/Startup.cs
closes https://github.com/aspnetboilerplate/aspnetboilerplate/issues/6310
=> use UnicodeRanges.All as TextEncoder

aspnet-core/src/AbpCompanyName.AbpProjectName.Core/AbpCompanyName.AbpProjectName.Core.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Core/Authorization/Users/UserManager.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.Migrator/AbpCompanyName.AbpProjectName.Migrator.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Core/AbpCompanyName.AbpProjectName.Web.Core.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Host/AbpCompanyName.AbpProjectName.Web.Host.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/AbpCompanyName.AbpProjectName.Web.Mvc.csproj, aspnet-core/test/AbpCompanyName.AbpProjectName.Tests/AbpCompanyName.AbpProjectName.Tests.csproj, aspnet-core/test/AbpCompanyName.AbpProjectName.Web.Tests/AbpCompanyName.AbpProjectName.Web.Tests.csproj
related https://github.com/aspnetboilerplate/aspnetboilerplate/issues/6385
=> Upgrade to Abp v7.1.0 

angular/angular.json, angular/e2e/tsconfig.json, angular/src/app/app.component.spec.ts, angular/src/tsconfig.spec.json
Fixes https://github.com/aspnetboilerplate/aspnetboilerplate/issues/6378
=> fixes angular unit test problems

aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Views/Account/_Scripts.cshtml, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Views/Shared/Layout/_Scripts.cshtml
Related issue : https://github.com/aspnetboilerplate/aspnetboilerplate/issues/6421
=> Scripts updated with GetScriptsResponsePerUserConfiguration

aspnet-core/src/AbpCompanyName.AbpProjectName.EntityFrameworkCore/AbpCompanyName.AbpProjectName.EntityFrameworkCore.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Core/AbpCompanyName.AbpProjectName.Web.Core.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Host/AbpCompanyName.AbpProjectName.Web.Host.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/AbpCompanyName.AbpProjectName.Web.Mvc.csproj, aspnet-core/test/AbpCompanyName.AbpProjectName.Tests/AbpCompanyName.AbpProjectName.Tests.csproj, aspnet-core/test/AbpCompanyName.AbpProjectName.Web.Tests/AbpCompanyName.AbpProjectName.Web.Tests.csproj
related https://github.com/aspnetboilerplate/aspnetboilerplate/issues/6438
=> Update packages to latest 

aspnet-core/src/AbpCompanyName.AbpProjectName.Core/AbpCompanyName.AbpProjectName.Core.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Core/AppVersionHelper.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.EntityFrameworkCore/Migrations/20220622074714_Upgrade_To_ABP_7.3.Designer.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.EntityFrameworkCore/Migrations/20220622074714_Upgrade_To_ABP_7.3.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.Migrator/AbpCompanyName.AbpProjectName.Migrator.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Core/AbpCompanyName.AbpProjectName.Web.Core.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Host/AbpCompanyName.AbpProjectName.Web.Host.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/AbpCompanyName.AbpProjectName.Web.Mvc.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/libman.json, aspnet-core/test/AbpCompanyName.AbpProjectName.Tests/AbpCompanyName.AbpProjectName.Tests.csproj, aspnet-core/test/AbpCompanyName.AbpProjectName.Web.Tests/AbpCompanyName.AbpProjectName.Web.Tests.csproj
related https://github.com/aspnetboilerplate/aspnetboilerplate/issues/6479
=> Update nuget packages

angular/src/app-initializer.ts, angular/src/shared/multi-tenancy/tenant-resolvers/query-string-tenant-resolver.ts
resolves https://github.com/aspnetboilerplate/aspnetboilerplate/issues/6633
=> Implemented QueryStringTenantResolver for Angular template

aspnet-core/src/AbpCompanyName.AbpProjectName.Core/AbpCompanyName.AbpProjectName.Core.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.EntityFrameworkCore/AbpCompanyName.AbpProjectName.EntityFrameworkCore.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Migrator/AbpCompanyName.AbpProjectName.Migrator.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Core/AbpCompanyName.AbpProjectName.Web.Core.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Host/AbpCompanyName.AbpProjectName.Web.Host.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/AbpCompanyName.AbpProjectName.Web.Mvc.csproj, aspnet-core/test/AbpCompanyName.AbpProjectName.Tests/AbpCompanyName.AbpProjectName.Tests.csproj, aspnet-core/test/AbpCompanyName.AbpProjectName.Web.Tests/AbpCompanyName.AbpProjectName.Web.Tests.csproj
Resolves [aspnetboilerplate/issues/6942](https://github.com/aspnetboilerplate/aspnetboilerplate/issues/6942)
ABP packages and other packages have been upgraded to the latest version
=> Upgraded to ABP 9.2

aspnet-core/src/AbpCompanyName.AbpProjectName.EntityFrameworkCore/Migrations/20240503071035_Upgraded_To_Abp_9_2.Designer.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.EntityFrameworkCore/Migrations/20240503071035_Upgraded_To_Abp_9_2.cs
Resolves [aspnetboilerplate/issues/6946](https://github.com/aspnetboilerplate/aspnetboilerplate/issues/6946)
New migration created for Abp 9.2
=> Added abp 9.2 migration

aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Host/Dockerfile, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Dockerfile
=> Update docker file to SDK 8

angular/angular.json
When I tried to create a directive, the following error ocurred: 
I just add the project name in @schematics/angular:directive, and the error was resolved.
=> Fix angular.json

angular/src/app/about/about-routing.module.ts, angular/src/app/about/about.module.ts, angular/src/app/app-routing.module.ts, angular/src/app/app.module.ts, angular/src/app/home/home-routing.module.ts, angular/src/app/home/home.module.ts, angular/src/app/roles/roles-routing.module.ts, angular/src/app/roles/roles.module.ts, angular/src/app/tenants/tenants-routing.module.ts, angular/src/app/tenants/tenants.module.ts, angular/src/app/users/users-routing.module.ts, angular/src/app/users/users.module.ts, angular/src/shared/shared.module.ts
Resolves [aspnetboilerplate/issues/6395](https://github.com/aspnetboilerplate/aspnetboilerplate/issues/6395)
=> Refactored angular template to use the module per page approach

aspnet-core/src/AbpCompanyName.AbpProjectName.Core/Localization/SourceFiles/AbpProjectName-tr.xml, aspnet-core/src/AbpCompanyName.AbpProjectName.Core/Localization/SourceFiles/AbpProjectName.xml, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Controllers/AccountController.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Startup/AuthConfigurer.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Views/Account/Error403.cshtml, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Views/Account/_Layout.cshtml, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/wwwroot/view-resources/Views/Account/Error403.css, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/wwwroot/view-resources/Views/Account/Error403.scss
Related https://github.com/aspnetboilerplate/aspnetboilerplate/issues/6681
Final result
=> Add error 403 page

angular/src/shared/service-proxies/service-proxies.ts, aspnet-core/src/AbpCompanyName.AbpProjectName.Core/AbpCompanyName.AbpProjectName.Core.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.EntityFrameworkCore/AbpCompanyName.AbpProjectName.EntityFrameworkCore.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Migrator/AbpCompanyName.AbpProjectName.Migrator.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Core/AbpCompanyName.AbpProjectName.Web.Core.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Host/AbpCompanyName.AbpProjectName.Web.Host.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/AbpCompanyName.AbpProjectName.Web.Mvc.csproj, aspnet-core/test/AbpCompanyName.AbpProjectName.Tests/AbpCompanyName.AbpProjectName.Tests.csproj, aspnet-core/test/AbpCompanyName.AbpProjectName.Web.Tests/AbpCompanyName.AbpProjectName.Web.Tests.csproj
Resolves [aspnetboilerplate/issues/7021](https://github.com/aspnetboilerplate/aspnetboilerplate/issues/7021)
Abp packages have been upgraded to version 9.4. Other required packages have also been updated to the latest version.
=> Upgraded to Abp 9.4

aspnet-core/src/AbpCompanyName.AbpProjectName.Core/AbpCompanyName.AbpProjectName.Core.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Migrator/AbpCompanyName.AbpProjectName.Migrator.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Core/AbpCompanyName.AbpProjectName.Web.Core.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Host/AbpCompanyName.AbpProjectName.Web.Host.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/AbpCompanyName.AbpProjectName.Web.Mvc.csproj, aspnet-core/test/AbpCompanyName.AbpProjectName.Tests/AbpCompanyName.AbpProjectName.Tests.csproj, aspnet-core/test/AbpCompanyName.AbpProjectName.Web.Tests/AbpCompanyName.AbpProjectName.Web.Tests.csproj
Resolves [aspnetboilerplate/issues/7027](https://github.com/aspnetboilerplate/aspnetboilerplate/issues/7027)
=> Upgraded to Abp 9.4.1

angular/src/tsconfig.json
Resolves https://github.com/aspnetboilerplate/aspnetboilerplate/issues/7023
=> Fix angular build error

angular/src/app/users/create-user/create-user-dialog.component.html, angular/src/app/users/edit-user/edit-user-dialog.component.html
Resolves [aspnetboilerplate/issues/7057](https://github.com/aspnetboilerplate/aspnetboilerplate/issues/7057)
User input max length values ​​have been corrected according to the limitation defined in AbpUserBase
=> Fixed user input max length value

aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Host/Startup/Startup.cs
Small PR - updates the correct location of the license file.
=> Update license reference

aspnet-core/src/AbpCompanyName.AbpProjectName.EntityFrameworkCore/Migrations/20250114124801_Upgraded_To_Abp_10_0.Designer.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.EntityFrameworkCore/Migrations/20250114124801_Upgraded_To_Abp_10_0.cs
Resolves [aspnetboilerplate/issues/7096](https://github.com/aspnetboilerplate/aspnetboilerplate/issues/7096)
A migration was created to reflect the changes coming with Abp 10.0 to the database.
=> Updated Migrations for Abp 10.0

aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Host/appsettings.json, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/appsettings.json
Resolves [aspnetboilerplate/issues/7100](https://github.com/aspnetboilerplate/aspnetboilerplate/issues/7100)
Database query logs in the console were removed when the application was run.
=> Updated logging configuration in appsettings.json
