aspnetboilerplate/module-zero-core-template

aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Views/Account/Login.cshtml, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Views/Account/Register.cshtml
Current lowercase usage:
- `<form asp-action="ExternalLogin" method="post">` in [Login.cshtml#L91](https://github.com/aspnetboilerplate/module-zero-core-template/blob/cdd334959c650568e556cd0b40cfe00595250c81/aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Views/Account/Login.cshtml#L91)
Reasons for choosing lowercase:
- IntelliSense suggests `post`
- ASP.NET defaults to `post`
Other considerations:
- HTML5 is case-*in*sensitive
- XHTML requires lowercase
- HTTP sends uppercase regardless
=> Standardise lowercase 'post' using asp.net default

aspnet-core/src/AbpCompanyName.AbpProjectName.Application/Roles/RoleAppService.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.Core/Localization/SourceFiles/AbpProjectName.xml
1. Add missing localization used in edit modals: e0ea3ff
https://github.com/aspnetboilerplate/module-zero-core-template/blob/d98b80c6d42e94d2fbb0a77a58fbecc85ea03ca7/aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Views/Roles/_EditRoleModal.cshtml#L6
https://github.com/aspnetboilerplate/module-zero-core-template/blob/d98b80c6d42e94d2fbb0a77a58fbecc85ea03ca7/aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Views/Tenants/_EditTenantModal.cshtml#L8
https://github.com/aspnetboilerplate/module-zero-core-template/blob/d98b80c6d42e94d2fbb0a77a58fbecc85ea03ca7/aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Views/Users/_EditUserModal.cshtml#L6
=> Add missing localization used in various classes

aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Host/Startup/SecurityRequirementsOperationFilter.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Host/Startup/Startup.cs
Fixes aspnetboilerplate/aspnetboilerplate#2302
This doesn't seem to be supported for `apiKey` or `bearerAuth`, only *scopes* in `oauth2`.
References:
https://github.com/domaindrivendev/Swashbuckle.AspNetCore#add-security-definitions-and-requirements
=> Add swagger security definitions and requirements

aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Views/Roles/Index.cshtml
This is due to the `label for="{id}"` in
https://github.com/aspnetboilerplate/module-zero-core-template/blob/fbcf9eb862500e11a3f56f16f2e457634740e14d/aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Views/Roles/_EditRoleModal.cshtml#L51-L52
referencing the same `id` in
https://github.com/aspnetboilerplate/module-zero-core-template/blob/fbcf9eb862500e11a3f56f16f2e457634740e14d/aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Views/Roles/Index.cshtml#L118-L119
I decided to modify `Roles/Index.cshtml` instead of `_EditRoleModal.cshtml`
```html
<input type="checkbox" name="permission" value="@permission.Name" class="filled-in" id="permission-@permission.Name" checked="checked" />
<label for="permission-@permission.Name">@permission.DisplayName</label>
```
to be consistent with …
=> Fix checkbox not working when edit role permission

aspnet-core/src/AbpCompanyName.AbpProjectName.EntityFrameworkCore/EntityFrameworkCore/Seed/Host/DefaultLanguagesCreator.cs
Add the Japanese language as an available language.  The .xml file is in the project, so there is no clear reason on why it was excluded to begin with.  Tested locally and the language loads and the flag is displayed.
=> Add Japanese language to DefaultLanguagesCreator

angular/package.json, angular/src/polyfills.ts
When generating a template, I was unable to run the angular project. It complained about web-animations-js.
From this commit a week ago, it appears this was added to the polyfill.ts but it wasn't added to the packages, so it wasn't being brought in.
https://github.com/aspnetboilerplate/module-zero-core-template/commit/3c0856bb5e6c19cbcf7baf17b95fd1b72b872960
=> added web-animations-js to package.json

aspnet-core/src/AbpCompanyName.AbpProjectName.EntityFrameworkCore/EntityFrameworkCore/Seed/Host/HostRoleAndUserCreator.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.EntityFrameworkCore/EntityFrameworkCore/Seed/Tenants/TenantRoleAndUserBuilder.cs
Otherwise when new permissions are added later, the current admins don't get those new permissions granted.
The implementation makes sure that already granted permissions aren't granted again, and nothing happens when no new permissions are added.
=> Always grant all permissions to admin users during seed

aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Host/wwwroot/swagger/ui/on-complete.js
see securitydefinition defined in startup.cs 
https://github.com/aspnetboilerplate/module-zero-core-template/blob/8eb2944430aa814557112c21769c70231f69b911/aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Host/Startup/Startup.cs#L72
see also https://github.com/swagger-api/swagger-ui/issues/1244#issuecomment-245638234
=> the key for clientAuthorizations.add must be the same as the one of the SecurityDefinition

aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Controllers/AccountController.cs
Fixes https://forum.aspnetboilerplate.com/viewtopic.php?p=23831
Actual parameter in [Microsoft.AspNetCore.Identity/SignInManager.cs#L549-L588](https://github.com/aspnet/Identity/blob/eb3ff7fc32dbfff65a1ba6dfdca16487e0f6fc41/src/Microsoft.AspNetCore.Identity/SignInManager.cs#L549-L588):
```c#
/// <param name="expectedXsrf">Flag indication whether a Cross Site Request Forgery token was expected in the current request.</param>
/// <returns>...</returns>
public virtual async Task<ExternalLoginInfo> GetExternalLoginInfoAsync(string expectedXsrf = null)
```
=> Remove authSchema parameter passed as expectedXsrf

aspnet-core/src/AbpCompanyName.AbpProjectName.Migrator/Program.cs
In order to use Migrator in Continuous Integration pipelines (which runs unattended), it should have a fully silent mode. So I suggest making the wait for exit confirmation at the end optional. I reused `_skipConnVerification` since no backward compatibility required for ABP templates.  
BTW I doubt `_skipConnVerification` was correctly named in the first place, so feel free to alter the PR (add another optional parameter defaulting to wait for confirmation) to give the same effect.
=> Remove confirmation for exit with no verification

angular/src/account/account.component.less, angular/src/account/login/login.component.html, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Views/Account/Login.cshtml, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/wwwroot/view-resources/Views/Account/Login.css, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/wwwroot/view-resources/Views/Account/Login.less
In [login.js](https://github.com/aspnetboilerplate/module-zero-core-template/blob/master/aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/wwwroot/view-resources/Views/Account/Login.js#L26), `#LoginArea` is used as the element for busy indicator.
However, after BSB Admin theme is implemented, `#LoginArea` was removed.
To keep the behavior of setting busy indicator for login, I would suggest removing the styles apply to `#LoginArea` since it's replace by `card` in BSB Admin, and adding back the element id for login area
=> Fixed login page styles

aspnet-core/src/AbpCompanyName.AbpProjectName.Migrator/MultiTenantMigrateExecuter.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.Migrator/Program.cs
Using the migrator in CI (Continuous Integration) pipelines where it runs unattended, it is important to know how things went for it, so as to make the build/test fail.
This PR adds migrator the ability to tell whether it run successfully or not by emitting the exit code. Currently, it is always returning 0 to the operating system which makes it infeasible (parsing logs is an option) to tell if something went wrong.
=> Add exit code to migrator to signify program's exit status

aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Host/Properties/launchSettings.json
With current template `dotnet run` starts Web.Host application on port 5000 which is inconvenient.
With my change it will start on 21021.
See https://stackoverflow.com/a/49000939/606007 for details.
=> Added settings to change Kestrel port when run with dotnet run

aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Host/Startup/SecurityRequirementsOperationFilter.cs
[https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/759](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/759)
fix this warning 
As of v3.0.0, the canonical way of accessing action or controller attributes in a filter is via context.MethodInfo
=> Replace the Obsolete method of SecurityRequirementsOperationFilter

aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Host/wwwroot/swagger/ui/index.html
Previously it would send "Authorization: Bearer null" when no token was present
=> Only send Authorization header if token is present

aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Host/Properties/launchSettings.json
Typo in Web.Host project launch settings configuration is preventing a freshly downloaded Angular/ASP.NET Core startup template to run.
=> Fixed incorrect port number in launch settings

aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Host/Startup/Startup.cs
To sure swagger endpoint url is formed correctly.
`_appConfiguration[App:ServerRootAddress]` may or may not have url ends with `"/"`
=> Fix swagger endpoint url

aspnet-core/src/AbpCompanyName.AbpProjectName.Application/Users/Dto/PagedUserResultRequestDto.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.Application/Users/IUserAppService.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.Application/Users/UserAppService.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.Core/Localization/SourceFiles/AbpProjectName-zh-Hans.xml, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Controllers/UsersController.cs, aspnet-core/test/AbpCompanyName.AbpProjectName.Tests/Users/UserAppService_Tests.cs, rename.ps1, vue/src/lib/appconst.ts, vue/src/lib/url.ts, vue/src/lib/util.ts, vue/src/views/main.less, vue/src/views/setting/role/role.vue, vue/src/views/setting/tenant/tenant.vue, vue/src/views/setting/user/user.vue, vue/vue.config.js
fix some issues in vue template:
1. Fix css in main.less when build for production
2. Fix vue.config.js, files should be copy into dist folder when build for production
3. Fix appconst.ts defaultLocalizationSourceName should be AbpProjectName
4. Sample code about pagerequest of request a list in user.vue role.vue tenant.vue has a sql injection problem, fix user.vue and add todo for role.vue tenant.vue, also, add console.warn in Util.buildFilters
5. Replace PagedResultRequest with PagedUserResultRequest in IUserAppService as sample code deal with query filters.
6. Add rename.ps1 for test
=> fix issues in vue template

angular/AbpCompanyName.AbpProjectName.AngularUI.csproj
The difference in casing between the file and the
reference in the project file produced errors building
on Azure DevOps on an Ubuntu system.
=> Fix casing on App.config to enable linux builds

angular/src/account/account.component.ts, angular/src/shared/core.less
There are 3 modifications here:
- Duplicated code for the "@indigo" theme removed;
- Without the "!important", the .mat-primary styles are not overridden as it should;
- On the AccountComponent, just adding a new class to the <body> don't completely reset the body class existent definitions, if there is any.
=> Small improvements for theming

angular/src/app/tenants/tenants.component.html, angular/src/app/users/users.component.html, angular/src/bsb-theme/css/style.css
The angular\src\bsb-theme\css\style.min.css doesn't look like an angular\src\bsb-theme\css\style.css minified, so, I left the style.min.css untouched.
=> Material Icons checkbox inline styles removed

reactjs/src/services/user/userService.ts
The update in the userService method returned the parent object (AxiosResponse) instead of the GetUserOutput. Corrected in the same way as the code is written in the other services.
=> Bugfix in userService which generates an error after updating a user

aspnet-core/src/AbpCompanyName.AbpProjectName.Application/AbpCompanyName.AbpProjectName.Application.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Core/AbpCompanyName.AbpProjectName.Core.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.EntityFrameworkCore/AbpCompanyName.AbpProjectName.EntityFrameworkCore.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Migrator/AbpCompanyName.AbpProjectName.Migrator.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Core/AbpCompanyName.AbpProjectName.Web.Core.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Core/AbpProjectNameWebCoreModule.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Core/Configuration/HostingEnvironmentExtensions.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Host/AbpCompanyName.AbpProjectName.Web.Host.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Host/Startup/AbpProjectNameWebHostModule.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Host/Startup/Startup.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/AbpCompanyName.AbpProjectName.Web.Mvc.csproj, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Resources/WebResourceManager.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Startup/AbpProjectNameWebMvcModule.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Startup/Startup.cs
- Replace `IHostingEnvironment` with `IWebHostEnvironment`(This type is obsolete and will be removed in a future version. The recommended alternative is `Microsoft.AspNetCore.Hosting.IWebHostEnvironment`) .
- `InProcess` already the default hosting mode.
- Remove `<FrameworkReference Include="Microsoft.AspNetCore.App" />` in `csproj` 
https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#implicit-package-references
=> Remove unnecessary cookie scheme.

angular/package.json
Warnings when running `yarn` command before the change proposed in this PR:
```
warning " > @angular/common@8.2.4" has incorrect peer dependency "rxjs@^6.4.0".
warning " > @angular/core@8.2.4" has incorrect peer dependency "rxjs@^6.4.0".
warning " > @angular/core@8.2.4" has incorrect peer dependency "zone.js@~0.9.1".
warning " > @angular/forms@8.2.4" has incorrect peer dependency "rxjs@^6.4.0".
warning " > @angular/router@8.2.4" has incorrect peer dependency "rxjs@^6.4.0".
warning " > abp-ng2-module@4.0.0" has incorrect peer dependency "abp-web-resources@^3.8.4".
```
=> Update dependencies to satisfy peer dependencies for Angular project

reactjs/src/lib/signalRAspNetCoreHelper.ts, vue/src/lib/SignalRAspNetCoreHelper.ts, vue/src/lib/appconst.ts
in `abp.signalr-client.js` ,there are two main fucntions  about signalR connection
https://github.com/aspnetboilerplate/aspnetboilerplate/blob/fc11d4ca6fc7044ad5ffce7fc18f5519e0ef71fd/src/Abp.Web.Resources/Abp/Framework/scripts/libs/abp.signalr-client.js#L64
and 
https://github.com/aspnetboilerplate/aspnetboilerplate/blob/fc11d4ca6fc7044ad5ffce7fc18f5519e0ef71fd/src/Abp.Web.Resources/Abp/Framework/scripts/libs/abp.signalr-client.js#L86
if the `remoteServiceBaseUrl` is null or '',  i got this 404 error
apart from this，when is use this:
```js
Util.abp.signalr.startConnection("/signalr-testHub", function(connection) {})
```
i also get 404 error,it will connect to a client url not a server url,no matter i put `signalr-testHub` or  `/signalr-testHub`
i must set an absolute remote server hub …
=> Fix error on signalR connection

aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Views/Shared/Components/SideBarMenu/Default.cshtml, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Views/Shared/Components/SideBarMenu/UserMenuItemExtensions.cs, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Views/Shared/Components/SideBarMenu/_MenuItem.cshtml
Added an extension method in `Web.Mvc` project to easily change the ordering across the project.
```c#
public static IOrderedEnumerable<UserMenuItem> OrderByCustom(this IEnumerable<UserMenuItem> menuItems)
{
return menuItems
.OrderBy(menuItem => menuItem.Order)
.ThenBy(menuItem => menuItem.DisplayName);
}
```
Related: [https://stackoverflow.com/questions/60318625/menuitemdefinition-order](https://stackoverflow.com/q/60318625/8601760) (v4.x template)
=> Order user menu items by order and display name

aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Host/Startup/Startup.cs
OpenApiInfo:
https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-3.1&tabs=visual-studio#api-info-and-description
Swagger options.DisplayRequestDuration:
https://github.com/domaindrivendev/Swashbuckle/issues/1295
=> Swagger full OpenApiInfo and display request duration

aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Views/Shared/Components/AccountLanguages/Default.cshtml, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Views/Shared/Components/RightNavbarLanguageSwitch/Default.cshtml
Reverts aspnetboilerplate/module-zero-core-template#537
`@Url.Action()` seems to escape the route params and causing double encoding with `HttpUtility.UrlEncode()`
=> Revert "Include query string in return url for link to change culture"

aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Views/Shared/Components/AccountLanguages/Default.cshtml, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Views/Shared/Components/RightNavbarLanguageSwitch/Default.cshtml
Reverts https://github.com/aspnetboilerplate/module-zero-core-template/pull/541.
And removed url encoding when constructing via `Url.Action()`
=> Remove url encode when constructing via Url.Action

aspnet-core/src/AbpCompanyName.AbpProjectName.Core/Configuration/AppConfigurations.cs
while running on .net6, it will occure an error:
> Unhandled exception. System.IO.FileNotFoundException: The configuration file 'secrets.json' was not found and is not optional.
=> fix 'secrets.json' was not found

aspnet-core/Dockerfile
Dockerfile uses old images of ASPNET and SDK of version 6.0 instead of 7.0.
=> Dockerfile .NET7

angular/package.json
According to the ngx-bootstrap version compatibility list the version 12.x.x is the compatible one with Angular 17.
[https://github.com/valor-software/ngx-bootstrap?tab=readme-ov-file#compatibility](https://github.com/valor-software/ngx-bootstrap?tab=readme-ov-file#compatibility)
=> Update ngx-bootstrap to solve compatibility problem with Angular 17

aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Startup/Startup.cs
Resolves [aspnetboilerplate/issues/6971](https://github.com/aspnetboilerplate/aspnetboilerplate/issues/6971)
AddRazorRuntimeCompilation has been removed from startup.cs. The reason why it is removed here is at run time and if they want to add a unique CSS, which is the best thing, there is a high probability that the CSS changes will not appear at run time. For this reason, AddRazorRuntimeCompilation has been removed. According to the recommendations in the Microsoft documentation, it is recommended to use hot reload in order to see the changes in the development environment. It is written in the [document ](https://learn.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-8.0&tabs=visual-studio)that AddRazorRuntimeCompilation disables hot reload.
=> Removed AddRazorRuntimeCompilation from Startup

angular/src/shared/core.less
[Resolves aspnetboilerplate/issues/6994](https://github.com/aspnetboilerplate/aspnetboilerplate/issues/6994)
Toast notification title space has been removed
=> Hided .swal2-title elements by changing display to none

aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Host/Properties/launchSettings.json, aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Properties/launchSettings.json
Updated launchSettings.json to use applicationUrl instead of launchUrl.
This will allow the project to be run as a launch profile instead of the IIS Express profile.
Otherwise when running the project with the project profile, the web browser opens but does not connect to the website.
Fixes issue https://github.com/aspnetboilerplate/aspnetboilerplate/issues/7052
=> Updated launchSettings.json
